# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_AR.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
import os
import sys
import matplotlib
matplotlib.use("TkAgg")
import HW4_SIFT_test as s
from HW4_SIFT_test import *
import HW1_Chess as c
from HW1_Chess import *
import HW2_AR as a
from HW2_AR import *
import HW3_Disparity as d
from HW3_Disparity import *



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 443)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 131, 371))
        self.groupBox.setObjectName("groupBox")
#Select a folder
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(0, 80, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.getFolder)
#Select an image for disparity
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 170, 131, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.getImage1)
#Select second image hfor disparity
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 270, 131, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.getImage2)
        
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 20, 161, 371))
        self.groupBox_2.setObjectName("groupBox_2")
#Showing the corners
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 40, 141, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.displayCorners)
#Display the Distortion matrix       
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 141, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.displayIntrinsicMatrix)
#Display the Distortion matrix       
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 240, 141, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.displayDistortionMatrix)
#Display final result of undistorted images
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 300, 141, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.displayUndistorted)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 120, 141, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 60, 141, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.displayExtrinsicMatrix)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("1")
        self.comboBox.addItem("2")
        self.comboBox.addItem("3")
        self.comboBox.addItem("4")
        self.comboBox.addItem("5")
        self.comboBox.addItem("6")
        self.comboBox.addItem("7")
        self.comboBox.addItem("8")
        self.comboBox.addItem("9")
        self.comboBox.addItem("10")
        self.comboBox.addItem("11")
        self.comboBox.addItem("12")
        self.comboBox.addItem("13")
        self.comboBox.addItem("14")
        self.comboBox.addItem("15")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 20, 201, 371))
        self.groupBox_4.setObjectName("groupBox_4")
#Show words on board
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 170, 201, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.AR_horizontal)
#Show words on board vertically       
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 250, 201, 32))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.AR_vertical)
        
#Input the word      
        self.WORD_INPUT = QtWidgets.QLineEdit(self.groupBox_4)
        self.WORD_INPUT.setGeometry(QtCore.QRect(20, 50, 171, 51)) 
        self.WORD_INPUT.setObjectName("WORD_INPUT")
        
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(530, 20, 181, 371))
        self.groupBox_5.setObjectName("groupBox_5")
#Disparity
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 170, 181, 32))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.disparity_map)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(720, 20, 171, 371))
        self.groupBox_6.setObjectName("groupBox_6")
 #Load image 1 for SIFT              
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 60, 113, 32))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.getImage1)
#Load image 2 for SIFT                  
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_14.setGeometry(QtCore.QRect(30, 130, 113, 32))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.getImage2)
 #Display SIFT keypoints       
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 210, 113, 32))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.displayKeypoints)
#Display keypoint matching
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 290, 171, 32))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.keypoint_matching)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(900, 20, 201, 371))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_17.setGeometry(QtCore.QRect(50, 40, 113, 32))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 80, 201, 32))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_19.setGeometry(QtCore.QRect(0, 130, 201, 32))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_20.setGeometry(QtCore.QRect(0, 190, 201, 32))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 250, 201, 32))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_22.setGeometry(QtCore.QRect(0, 310, 201, 32))
        self.pushButton_22.setObjectName("pushButton_22")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(1110, 60, 321, 271))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Load Image"))
        self.pushButton.setText(_translate("Form", "Load Folder"))
        self.pushButton_2.setText(_translate("Form", "Load Image_L"))
        self.pushButton_3.setText(_translate("Form", "Load Image_R"))
        self.groupBox_2.setTitle(_translate("Form", "1. Calibration"))
        self.pushButton_4.setText(_translate("Form", "1.1 Find Corners"))
        self.pushButton_5.setText(_translate("Form", "1.1 Find Intrinsic"))
        self.pushButton_6.setText(_translate("Form", "1.4 Find Distortion"))
        self.pushButton_7.setText(_translate("Form", "1.5 Show results"))
        self.groupBox_3.setTitle(_translate("Form", "1.3 Find Extrinsic"))
        self.pushButton_8.setText(_translate("Form", "1.3 Find Extrinsic"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "3"))
        self.comboBox.setItemText(3, _translate("Form", "4"))
        self.comboBox.setItemText(4, _translate("Form", "5"))
        self.comboBox.setItemText(5, _translate("Form", "6"))
        self.comboBox.setItemText(6, _translate("Form", "7"))
        self.comboBox.setItemText(7, _translate("Form", "8"))
        self.comboBox.setItemText(8, _translate("Form", "9"))
        self.comboBox.setItemText(9, _translate("Form", "10"))
        self.comboBox.setItemText(10, _translate("Form", "11"))
        self.comboBox.setItemText(11, _translate("Form", "12"))
        self.comboBox.setItemText(12, _translate("Form", "13"))
        self.comboBox.setItemText(13, _translate("Form", "14"))
        self.comboBox.setItemText(14, _translate("Form", "15"))
        self.groupBox_4.setTitle(_translate("Form", "2. Augmented Reality"))
        self.pushButton_9.setText(_translate("Form", "2.1 Show words on board"))
        self.pushButton_10.setText(_translate("Form", "2.2 Show words vertically"))
        self.groupBox_5.setTitle(_translate("Form", "3. Stereo Disparity Map"))
        self.pushButton_11.setText(_translate("Form", "3.1 Stereo Disparity Map"))
        self.groupBox_6.setTitle(_translate("Form", "4. SIFT"))
        self.pushButton_13.setText(_translate("Form", "Load Image 1"))
        self.pushButton_14.setText(_translate("Form", "Load Image 2"))
        self.pushButton_15.setText(_translate("Form", "4.1 Keypoints"))
        self.pushButton_16.setText(_translate("Form", "4.2 Matched Keypoints"))
        self.groupBox_7.setTitle(_translate("Form", "5. Resnet101 Test"))
        self.pushButton_17.setText(_translate("Form", "Load Image"))
        self.pushButton_18.setText(_translate("Form", "5.1 Show Trained Images"))
        self.pushButton_19.setText(_translate("Form", "5.2 Show Model Structure"))
        self.pushButton_20.setText(_translate("Form", "5.3 Show data augmentation"))
        self.pushButton_21.setText(_translate("Form", "5.4 Show accuracy and loss"))
        self.pushButton_22.setText(_translate("Form", "5.5 Inference"))

#SIFT actions
    def SIFT_keypoints():
        s.__annotations__
        
    def displayKeypoints(self):
        s.display_SIFT_keypoints(self.fileName1)
        
    def keypoint_matching(self):
        s.SIFT_keypoint_matching(self.fileName1,self.fileName2)

#Folder and File handling
    def getFolder(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        self.folder= QFileDialog.getExistingDirectory(None,'Select a folder')
        if self.folder:
            print(self.folder)
        
        
    def getImage1(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        self.fileName1, _ = QFileDialog.getOpenFileName(None,'Select an image file', '',"All Files (*);;Image Files (*.jpg, *.png, *.bmp)", options=options)
        if self.fileName1:
            print(self.fileName1)
        #s.read_image1(self.fileName1)
 
    def getImage2(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        self.fileName2, _ = QFileDialog.getOpenFileName(None,'Select an image file', '',"All Files (*);;Image Files (*.jpg, *.png, *.bmp)", options=options)
        if self.fileName2:
            print(self.fileName2)     
        #s.read_image2(self.fileName2)
        
#1.Calibration
    def displayCorners(self):
        c.show_corners(self.folder)
    
    def displayIntrinsicMatrix(self):
        c.displayIntrinsicMatrix(self.folder)
        
    def displayDistortionMatrix(self):
        c.displayDistortionMatrix(self.folder)
        
    def displayExtrinsicMatrix(self):
        c.displayExtrinsicMatrix(self.folder,self.comboBox.currentIndex())

    def displayUndistorted(self):
        c.displayUndistortedImages(self.folder)

#AR

    def AR_horizontal(self):
        f = str(self.WORD_INPUT.text())
        a.AR_horizontal_words(self.folder,f) 
        
    def AR_vertical(self):
        f = str(self.WORD_INPUT.text())
        a.AR_vertical_words(self.folder,f) 
        
#Disparity
    def disparity_map(self):
        d.disparity_map(self.fileName1,self.fileName2)     

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
